repos:
  - repo: local
    hooks:
      - id: pytest
        name: Tests
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: black
        name: Black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        args: [--line-length=100]
        language: system
        require_serial: true
        types: [python]
      - id: pydocstyle
        name: DocStyle
        description: "Pydocstyle is a static analysis tool for checking compliance with Python docstring conventions"
        entry: pydocstyle
        args:
          [
            "--ignore=D100,D101,D103,D107",
          ]
        language: system
        types: [python]
      - id: isort
        name: Reorder python imports
        description: "This hook reorders imports in python files."
        entry: isort
        args: [--force-single-line-imports]
        require_serial: true
        language: system
        types: [python]
      - id: flake8
        name: Flake8
        description: "`flake8` is a command-line utility for enforcing style consistency across Python projects."
        entry: flake8
        args: [--max-line-length=100, --max-complexity=12]
        language: system
        require_serial: true
        types: [python]
      - id: safety
        name: Dependecies security
        entry: safety check
        pass_filenames: false
        language: system
      - id: bandit
        name: Python security
        entry: bandit
        args: [-l, --recursive, --exclude=tests]
        pass_filenames: true
        language: system
        types: [python]
      - id: mypy
        name: Python typing
        entry: poetry run mypy
        args: ["--ignore-missing-imports"]
        pass_filenames: true
        language: system
        types: [python]
