name: Code Check

on: pull_request

jobs:
  install:
    name: Install requirements
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
      #----------------------------------------------
      #             install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
  code-check:
    name: Code checks
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        check-type:
          ["flake8", "black", "isort", "bandit", "safety", "pydocstyle", "mypy"]
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      #----------------------------------------------
      #              Run each pre-commit check
      #----------------------------------------------
      - name: Check ${{ matrix.check-type }}
        run: |
          pre-commit run ${{ matrix.check-type }} --all-files
